/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SittersRouteImport } from './routes/sitters'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JaxstayPromiseRouteImport } from './routes/jaxstay-promise'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HelpRouteImport } from './routes/help'
import { Route as BecomeASitterRouteImport } from './routes/become-a-sitter'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SittersSitterIdRouteImport } from './routes/sitters.$sitterId'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedSitterTestRouteImport } from './routes/_authenticated/sitter-test'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiStripeConnectStatusRouteImport } from './routes/api/stripe.connect-status'
import { Route as ApiStripeConnectOnboardRouteImport } from './routes/api/stripe.connect-onboard'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe.checkout'
import { Route as ApiBookingsRefundRouteImport } from './routes/api/bookings.refund'
import { Route as ApiBookingsCompleteRouteImport } from './routes/api/bookings.complete'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe.webhook'
import { Route as ApiPublicCronAutoReleasePayoutsRouteImport } from './routes/api/public/cron.auto-release-payouts'
import { Route as AuthenticatedBookingsBookingIdIntakeRouteImport } from './routes/_authenticated/bookings.$bookingId.intake'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SittersRoute = SittersRouteImport.update({
  id: '/sitters',
  path: '/sitters',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JaxstayPromiseRoute = JaxstayPromiseRouteImport.update({
  id: '/jaxstay-promise',
  path: '/jaxstay-promise',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeASitterRoute = BecomeASitterRouteImport.update({
  id: '/become-a-sitter',
  path: '/become-a-sitter',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SittersSitterIdRoute = SittersSitterIdRouteImport.update({
  id: '/$sitterId',
  path: '/$sitterId',
  getParentRoute: () => SittersRoute,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSitterTestRoute = AuthenticatedSitterTestRouteImport.update({
  id: '/sitter-test',
  path: '/sitter-test',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiStripeConnectStatusRoute = ApiStripeConnectStatusRouteImport.update({
  id: '/api/stripe/connect-status',
  path: '/api/stripe/connect-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeConnectOnboardRoute = ApiStripeConnectOnboardRouteImport.update({
  id: '/api/stripe/connect-onboard',
  path: '/api/stripe/connect-onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRefundRoute = ApiBookingsRefundRouteImport.update({
  id: '/api/bookings/refund',
  path: '/api/bookings/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsCompleteRoute = ApiBookingsCompleteRouteImport.update({
  id: '/api/bookings/complete',
  path: '/api/bookings/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAutoReleasePayoutsRoute =
  ApiPublicCronAutoReleasePayoutsRouteImport.update({
    id: '/api/public/cron/auto-release-payouts',
    path: '/api/public/cron/auto-release-payouts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBookingsBookingIdIntakeRoute =
  AuthenticatedBookingsBookingIdIntakeRouteImport.update({
    id: '/$bookingId/intake',
    path: '/$bookingId/intake',
    getParentRoute: () => AuthenticatedBookingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-sitter': typeof BecomeASitterRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jaxstay-promise': typeof JaxstayPromiseRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitters': typeof SittersRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sitter-test': typeof AuthenticatedSitterTestRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/sitters/$sitterId': typeof SittersSitterIdRoute
  '/api/bookings/complete': typeof ApiBookingsCompleteRoute
  '/api/bookings/refund': typeof ApiBookingsRefundRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/connect-onboard': typeof ApiStripeConnectOnboardRoute
  '/api/stripe/connect-status': typeof ApiStripeConnectStatusRoute
  '/bookings/$bookingId/intake': typeof AuthenticatedBookingsBookingIdIntakeRoute
  '/api/public/cron/auto-release-payouts': typeof ApiPublicCronAutoReleasePayoutsRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-sitter': typeof BecomeASitterRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jaxstay-promise': typeof JaxstayPromiseRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitters': typeof SittersRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sitter-test': typeof AuthenticatedSitterTestRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/sitters/$sitterId': typeof SittersSitterIdRoute
  '/api/bookings/complete': typeof ApiBookingsCompleteRoute
  '/api/bookings/refund': typeof ApiBookingsRefundRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/connect-onboard': typeof ApiStripeConnectOnboardRoute
  '/api/stripe/connect-status': typeof ApiStripeConnectStatusRoute
  '/bookings/$bookingId/intake': typeof AuthenticatedBookingsBookingIdIntakeRoute
  '/api/public/cron/auto-release-payouts': typeof ApiPublicCronAutoReleasePayoutsRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/become-a-sitter': typeof BecomeASitterRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jaxstay-promise': typeof JaxstayPromiseRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitters': typeof SittersRouteWithChildren
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sitter-test': typeof AuthenticatedSitterTestRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/sitters/$sitterId': typeof SittersSitterIdRoute
  '/api/bookings/complete': typeof ApiBookingsCompleteRoute
  '/api/bookings/refund': typeof ApiBookingsRefundRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/connect-onboard': typeof ApiStripeConnectOnboardRoute
  '/api/stripe/connect-status': typeof ApiStripeConnectStatusRoute
  '/_authenticated/bookings/$bookingId/intake': typeof AuthenticatedBookingsBookingIdIntakeRoute
  '/api/public/cron/auto-release-payouts': typeof ApiPublicCronAutoReleasePayoutsRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-a-sitter'
    | '/help'
    | '/how-it-works'
    | '/jaxstay-promise'
    | '/login'
    | '/privacy'
    | '/sitters'
    | '/terms'
    | '/admin'
    | '/bookings'
    | '/dashboard'
    | '/messages'
    | '/settings'
    | '/sitter-test'
    | '/welcome'
    | '/sitters/$sitterId'
    | '/api/bookings/complete'
    | '/api/bookings/refund'
    | '/api/stripe/checkout'
    | '/api/stripe/connect-onboard'
    | '/api/stripe/connect-status'
    | '/bookings/$bookingId/intake'
    | '/api/public/cron/auto-release-payouts'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-a-sitter'
    | '/help'
    | '/how-it-works'
    | '/jaxstay-promise'
    | '/login'
    | '/privacy'
    | '/sitters'
    | '/terms'
    | '/admin'
    | '/bookings'
    | '/dashboard'
    | '/messages'
    | '/settings'
    | '/sitter-test'
    | '/welcome'
    | '/sitters/$sitterId'
    | '/api/bookings/complete'
    | '/api/bookings/refund'
    | '/api/stripe/checkout'
    | '/api/stripe/connect-onboard'
    | '/api/stripe/connect-status'
    | '/bookings/$bookingId/intake'
    | '/api/public/cron/auto-release-payouts'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/become-a-sitter'
    | '/help'
    | '/how-it-works'
    | '/jaxstay-promise'
    | '/login'
    | '/privacy'
    | '/sitters'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/bookings'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/settings'
    | '/_authenticated/sitter-test'
    | '/_authenticated/welcome'
    | '/sitters/$sitterId'
    | '/api/bookings/complete'
    | '/api/bookings/refund'
    | '/api/stripe/checkout'
    | '/api/stripe/connect-onboard'
    | '/api/stripe/connect-status'
    | '/_authenticated/bookings/$bookingId/intake'
    | '/api/public/cron/auto-release-payouts'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BecomeASitterRoute: typeof BecomeASitterRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JaxstayPromiseRoute: typeof JaxstayPromiseRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SittersRoute: typeof SittersRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApiBookingsCompleteRoute: typeof ApiBookingsCompleteRoute
  ApiBookingsRefundRoute: typeof ApiBookingsRefundRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripeConnectOnboardRoute: typeof ApiStripeConnectOnboardRoute
  ApiStripeConnectStatusRoute: typeof ApiStripeConnectStatusRoute
  ApiPublicCronAutoReleasePayoutsRoute: typeof ApiPublicCronAutoReleasePayoutsRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitters': {
      id: '/sitters'
      path: '/sitters'
      fullPath: '/sitters'
      preLoaderRoute: typeof SittersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jaxstay-promise': {
      id: '/jaxstay-promise'
      path: '/jaxstay-promise'
      fullPath: '/jaxstay-promise'
      preLoaderRoute: typeof JaxstayPromiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-sitter': {
      id: '/become-a-sitter'
      path: '/become-a-sitter'
      fullPath: '/become-a-sitter'
      preLoaderRoute: typeof BecomeASitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitters/$sitterId': {
      id: '/sitters/$sitterId'
      path: '/$sitterId'
      fullPath: '/sitters/$sitterId'
      preLoaderRoute: typeof SittersSitterIdRouteImport
      parentRoute: typeof SittersRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sitter-test': {
      id: '/_authenticated/sitter-test'
      path: '/sitter-test'
      fullPath: '/sitter-test'
      preLoaderRoute: typeof AuthenticatedSitterTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/stripe/connect-status': {
      id: '/api/stripe/connect-status'
      path: '/api/stripe/connect-status'
      fullPath: '/api/stripe/connect-status'
      preLoaderRoute: typeof ApiStripeConnectStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/connect-onboard': {
      id: '/api/stripe/connect-onboard'
      path: '/api/stripe/connect-onboard'
      fullPath: '/api/stripe/connect-onboard'
      preLoaderRoute: typeof ApiStripeConnectOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/refund': {
      id: '/api/bookings/refund'
      path: '/api/bookings/refund'
      fullPath: '/api/bookings/refund'
      preLoaderRoute: typeof ApiBookingsRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/complete': {
      id: '/api/bookings/complete'
      path: '/api/bookings/complete'
      fullPath: '/api/bookings/complete'
      preLoaderRoute: typeof ApiBookingsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/auto-release-payouts': {
      id: '/api/public/cron/auto-release-payouts'
      path: '/api/public/cron/auto-release-payouts'
      fullPath: '/api/public/cron/auto-release-payouts'
      preLoaderRoute: typeof ApiPublicCronAutoReleasePayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings/$bookingId/intake': {
      id: '/_authenticated/bookings/$bookingId/intake'
      path: '/$bookingId/intake'
      fullPath: '/bookings/$bookingId/intake'
      preLoaderRoute: typeof AuthenticatedBookingsBookingIdIntakeRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
  }
}

interface AuthenticatedBookingsRouteChildren {
  AuthenticatedBookingsBookingIdIntakeRoute: typeof AuthenticatedBookingsBookingIdIntakeRoute
}

const AuthenticatedBookingsRouteChildren: AuthenticatedBookingsRouteChildren = {
  AuthenticatedBookingsBookingIdIntakeRoute:
    AuthenticatedBookingsBookingIdIntakeRoute,
}

const AuthenticatedBookingsRouteWithChildren =
  AuthenticatedBookingsRoute._addFileChildren(
    AuthenticatedBookingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSitterTestRoute: typeof AuthenticatedSitterTestRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSitterTestRoute: AuthenticatedSitterTestRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SittersRouteChildren {
  SittersSitterIdRoute: typeof SittersSitterIdRoute
}

const SittersRouteChildren: SittersRouteChildren = {
  SittersSitterIdRoute: SittersSitterIdRoute,
}

const SittersRouteWithChildren =
  SittersRoute._addFileChildren(SittersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BecomeASitterRoute: BecomeASitterRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  JaxstayPromiseRoute: JaxstayPromiseRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SittersRoute: SittersRouteWithChildren,
  TermsRoute: TermsRoute,
  ApiBookingsCompleteRoute: ApiBookingsCompleteRoute,
  ApiBookingsRefundRoute: ApiBookingsRefundRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripeConnectOnboardRoute: ApiStripeConnectOnboardRoute,
  ApiStripeConnectStatusRoute: ApiStripeConnectStatusRoute,
  ApiPublicCronAutoReleasePayoutsRoute: ApiPublicCronAutoReleasePayoutsRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
