// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://yxevdpejxepgxziprcmo.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4ZXZkcGVqeGVwZ3h6aXByY21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5MzI1MjUsImV4cCI6MjA5MzUwODUyNX0.1BzxlpdB9o15xLh8gnE7_FaDOJD-mrZPqpcMMgr8wCQ";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
  },
});